### ISSUE TITLE
SimpleTap

### ISSUE THREAD

**Issue by Imaroubat** [thebrumby/HotWalletClaimer#176]
2024-08-13 16:11:41 Initialising the SimpleTap: Wallet Auto-claim Python Script - Good Luck!
2024-08-13 16:12:03 Traceback (most recent call last):
2024-08-13 16:12:03   File "/usr/src/app/games/simpletap.py", line 237, in <module>
2024-08-13 16:12:03     main()
2024-08-13 16:12:03   File "/usr/src/app/games/simpletap.py", line 234, in main
2024-08-13 16:12:03     claimer.run()
2024-08-13 16:12:03   File "/usr/src/app/games/claimer.py", line 165, in run
2024-08-13 16:12:03     wait_time = self.full_claim()
2024-08-13 16:12:03              
2024-08-13 16:12:03    ^^^^^^^^^^^^^^^^^
2024-08-13 16:12:03   File "/usr/src/app/games/simpletap.py", line 86, in full_claim
2024-08-13 16:12:03     self.get_balance(False)
2024-08-13 16:12:03   File "/usr/src/app/games/simpletap.py", line 165, in get_balance
2024-08-13 16:12:03     if button: button.click()
2024-08-13 16:12:03                ^^^^^^^^^^^^^^
2024-08-13 16:12:03   File "/usr/src/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
2024-08-13 16:12:03     self._execute(Command.CLICK_ELEMENT)
2024-08-13 16:12:03   File "/usr/src/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
2024-08-13 16:12:03     return self._parent.execute(command, params)
2024-08-13 16:12:03            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-13 16:12:03   File "/usr/src/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
2024-08-13 16:12:03     self.error_handler.check_response(response)
2024-08-13 16:12:03   File "/usr/src/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024-08-13 16:12:03     raise exception_class(message, screen, stacktrace)
2024-08-13 16:12:03 selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="appbar-tab">...</div> is not clickable at point (118, 564). Other element would receive the click: <div class="boost_inner_scroll">...</div>
2024-08-13 16:12:03   (Session info: chrome-headless-shell=126.0.6478.114)
2024-08-13 16:12:03 Stacktrace:
2024-08-13 16:12:03 #0 0x55a6ec11f69a <unknown>
2024-08-13 16:12:03 #1 0x55a6ebe020dc <unknown>
2024-08-13 16:12:03 #2 0x55a6ebe556c6 <unknown>
2024-08-13 16:12:03 #3 0x55a6ebe53516 <unknown>
2024-08-13 16:12:03 #4 0x55a6ebe50ef7 <unknown>
2024-08-13 16:12:03 #5 0x55a6ebe4fd2c <unknown>
2024-08-13 16:12:03 #6 0x55a6ebe4340f <unknown>
2024-08-13 16:12:03 #7 0x55a6ebe71872 <unknown>
2024-08-13 16:12:03 #8 0x55a6ebe42d89 <unknown>
2024-08-13 16:12:03 #9 0x55a6ebe71a3e <unknown>
2024-08-13 16:12:03 #10 0x55a6ebe905c3 <unknown>
2024-08-13 16:12:03 #11 0x55a6ebe71613 <unknown>
2024-08-13 16:12:03 #12 0x55a6ebe414f7 <unknown>
2024-08-13 16:12:03 #13 0x55a6ebe41e4e <unknown>
2024-08-13 16:12:03 #14 0x55a6ec0e586b <unknown>
2024-08-13 16:12:03 #15 0x55a6ec0e9911 <unknown>
2024-08-13 16:12:03 #16 0x55a6ec0d135e <unknown>
2024-08-13 16:12:03 #17 0x55a6ec0ea472 <unknown>
2024-08-13 16:12:03 #18 0x55a6ec0b5cbf <unknown>
2024-08-13 16:12:03 #19 0x55a6ec10f098 <unknown>
2024-08-13 16:12:03 #20 0x55a6ec10f270 <unknown>
2024-08-13 16:12:03 #21 0x55a6ec11e7cc <unknown>
2024-08-13 16:12:03 #22 0x7f7308c8fa94 <unknown>
2024-08-13 16:12:03 #23 0x7f7308d1cc3c <unknown>
2024-08-13 16:12:04 Initialising the SimpleTap: Wallet Auto-claim Python Script - Good Luck!
2024-08-13 16:12:26 Traceback (most recent call last):

**Comment by thebrumby** [comment]
https://github.com/thebrumby/HotWalletClaimer/issues/166

No evidence you followed the trouble shooting guide so closed.
