### ISSUE TITLE
Hot TypeError

### ISSUE THREAD

**Issue by prognt** [thebrumby/HotWalletClaimer#202]
```
Traceback (most recent call last):
2024-08-28T22:34:32.412467700Z   File "/usr/src/app/games/hot.py", line 292, in <module>
2024-08-28T22:34:32.818127300Z     main()
2024-08-28T22:34:32.854635500Z   File "/usr/src/app/games/hot.py", line 289, in main
2024-08-28T22:34:32.854664700Z     claimer.run()
2024-08-28T22:34:32.854669400Z   File "/usr/src/app/games/claimer.py", line 159, in run
2024-08-28T22:34:32.915411000Z     
2024-08-28T22:34:32.916817400Z wait_time = self.full_claim()
2024-08-28T22:34:32.916982400Z                 ^^^^^^^^^^^^^^^^^
2024-08-28T22:34:32.916991400Z   File "/usr/src/app/games/hot.py", line 124, in full_claim
2024-08-28T22:34:32.916995700Z     matches = re.findall(r'(\d+)([hm])', wait_time_text)
2024-08-28T22:34:32.916999000Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-28T22:34:32.917002800Z   File "/usr/lib/python3.12/re/__init__.py", line 217, in findall
2024-08-28T22:34:33.131738800Z     return _compile(pattern, flags).findall(string)
2024-08-28T22:34:33.131768200Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-28T22:34:33.131772900Z TypeError: expected string or bytes-like object, got 'bool'
```

**Comment by thebrumby** [comment]
https://github.com/thebrumby/HotWalletClaimer/issues/166
