### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by iamelected** [thebrumby/HotWalletClaimer#64]
Your session will be prefixed with: Hot-Alt:
Enter your unique Session Name here, or hit <enter> for the next sequential wallet: farmhot2
Proxy disabled in settings.
Traceback (most recent call last):
  File "/root/HotWalletClaimer/./games/hot-alt.py", line 1336, in <module>
    main()
  File "/root/HotWalletClaimer/./games/hot-alt.py", line 1276, in main
    next_steps()
  File "/root/HotWalletClaimer/./games/hot-alt.py", line 629, in next_steps
    launch_iframe()
  File "/root/HotWalletClaimer/./games/hot-alt.py", line 706, in launch_iframe
    driver = get_driver()
  File "/root/HotWalletClaimer/./games/hot-alt.py", line 330, in get_driver
    driver = setup_driver()
  File "/root/HotWalletClaimer/./games/hot-alt.py", line 271, in setup_driver
    proxy_auth_plugin_path = create_proxyauth_extension(
NameError: name 'create_proxyauth_extension' is not defined
Deactivating virtual environment...

**Comment by thebrumby** [comment]
Hi - we pushed a fix to the repository. Please `git pull` (standalone) or `./pull-gaemes.sh` (Docker) and test again.

Thanks.
