### ISSUE TITLE
HOT SSL certification error

### ISSUE THREAD

**Issue by howtoprogram** [thebrumby/HotWalletClaimer#78]
Got below error when try to run the game on Ubuntu 22, 24
```
CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Traceback (most recent call last):
  File "/home/john/data/HotWalletClaimer/./games/hot.py", line 1209, in <module>
    main()
  File "/home/john/data/HotWalletClaimer/./games/hot.py", line 1145, in main
    log_into_telegram()
  File "/home/john/data/HotWalletClaimer/./games/hot.py", line 407, in log_into_telegram
    if visible_QR_code():  # QR code not found
       ^^^^^^^^^^^^^^^^^
  File "/home/john/data/HotWalletClaimer/./games/hot.py", line 361, in visible_QR_code
    driver.get(url)
  File "/home/john/data/HotWalletClaimer/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/john/data/HotWalletClaimer/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/john/data/HotWalletClaimer/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
  (Session info: chrome-headless-shell=126.0.6478.114)
```

**Comment by thebrumby** [comment]
Hi, 

- Are you using Docker/Standalone?

- Are you using the built-in proxy?

- Have you tried using 

```
./launch.sh status
```
And then `delete HOT:Wallet1` or whatever your wallet ID is? and then setting up again. 

Thanks

**Comment by howtoprogram** [comment]
Hi,

Just start the script from Linux standalone.
